# Generated by Django 5.1.4 on 2024-12-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleregapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="telegramuser", name="first_name",),
        migrations.RemoveField(model_name="telegramuser", name="last_name",),
        migrations.AddField(
            model_name="telegramuser",
            name="auth_token",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
